Repository redacademy/wr-fall-2019, pull requests merged in 2019-12, with the labels that each got.

#8 update schema and .gitconfig
  .DS_Store
  client/ios/Podfile.lock
  server/prisma/datamodel.prisma
Labels: enhancement

#9 Kw bugfix delete .DS_Store
  .DS_Store
Labels: bug

#10 Kw feature packages
  client/ios/Podfile.lock
  client/package.json
  client/yarn.lock
Labels: enhancement

#12 add react-navigation-tabs package
  client/package.json
  client/yarn.lock
Labels: enhancement

#13 add react-native-reanimated package
  client/ios/Podfile.lock
  client/package.json
  client/yarn.lock
Labels: enhancement

#15 add react-native-check-box library
  client/package.json
  client/yarn.lock
Labels: enhancement

#16 Add @apollo/react-hooks apollo-client graphql
  client/package.json
  client/yarn.lock
Labels: enhancement

#17 add react-navigation-drawer library
  client/package.json
  client/yarn.lock
Labels: enhancement

#18 kw-add apollo-boost library
  client/package.json
  client/yarn.lock
Labels: enhancement

#19 kw-add @apollo/react-components
  client/package.json
  client/yarn.lock
Labels: enhancement

#20 kw-add react-apollo library
  client/package.json
  client/yarn.lock
Labels: enhancement

#14 Kw feature navigation
  .DS_Store
  client/.gitignore
  client/android/app/src/main/assets/fonts/FiraSans-Regular.ttf
  client/android/app/src/main/assets/fonts/NeueHaasDisplay-XThin.ttf
  client/index.js
  client/ios/WRFall2019.xcodeproj/project.pbxproj
  client/ios/WRFall2019/Info.plist
  client/js/App.js
  client/js/assets/buttonnav/BellIcon.png
  client/js/assets/buttonnav/bellred.png
  client/js/assets/buttonnav/bomb.png
  client/js/assets/buttonnav/bombred.png
  client/js/assets/buttonnav/earthlogo.png
  client/js/assets/buttonnav/earthlogored.png
  client/js/assets/headingelement/Burgermenu.png
  client/js/assets/headingelement/Headerlogo.png
  client/js/assets/headingelement/backarrow.png
  client/js/assets/headingelement/loginIcon.png
  client/js/config/styles.js
  client/js/navigation/DrawerNavigation.js
  client/js/navigation/DrawerScreen.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/navigation/config.js
  client/js/navigation/styles.js
  client/js/screens/About/About.js
  client/js/screens/About/AboutContainer.js
  client/js/screens/About/index.js
  client/js/screens/About/styles.js
  client/js/screens/Campaigns/Campaigns.js
  client/js/screens/Campaigns/CampaignsContainer.js
  client/js/screens/Campaigns/index.js
  client/js/screens/Campaigns/styles.js
  client/js/screens/Contact/Contact.js
  client/js/screens/Contact/ContactContainer.js
  client/js/screens/Contact/index.js
  client/js/screens/Contact/styles.js
  client/js/screens/Home/Home.js
  client/js/screens/Home/HomeContainer.js
  client/js/screens/Home/index.js
  client/js/screens/Home/styles.js
  client/js/screens/Notifications/Notifications.js
  client/js/screens/Notifications/NotificationsContainer.js
  client/js/screens/Notifications/index.js
  client/js/screens/Notifications/styles.js
  client/js/screens/Privacy/Privacy.js
  client/js/screens/Privacy/PrivacyContainer.js
  client/js/screens/Privacy/index.js
  client/js/screens/Privacy/styles.js
  client/js/screens/Terms/Terms.js
  client/js/screens/Terms/TermsContainer.js
  client/js/screens/Terms/index.js
  client/js/screens/Terms/styles.js
  client/react-native.config.js
Labels: enhancement

#25 Kw-feature drawerscreens
  client/js/assets/miscicons/homeaddress.png
  client/js/assets/miscicons/phoneicon.png
  client/js/assets/signinicons/EmailIcon.png
  client/js/screens/Contact/Contact.js
  client/js/screens/Contact/styles.js
  client/js/screens/Terms/Terms.js
  client/js/screens/Terms/styles.js
Labels: enhancement

#35 Cf feature notification
  client/js/components/Notification/Notification.js
  client/js/components/Notification/index.js
  client/js/components/Notification/styles.js
  client/js/components/NotificationCard/NotificationCard.js
  client/js/components/NotificationCard/index.js
  client/js/config/Theme/index.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/config.js
  client/js/navigation/styles.js
  client/js/screens/About/About.js
  client/js/screens/Notifications/Notifications.js
Labels: enhancement

#45 Cf feature confirmation
  client/js/App.js
  client/js/assets/artwork/Adbust@3x.png
  client/js/assets/fonts/FiraSans-Regular.ttf
  client/js/assets/fonts/NeueHaasDisplay-XThin.ttf
  client/js/config/Theme/index.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/Confirmation/Confirmation.js
  client/js/screens/Confirmation/index.js
  client/js/screens/Confirmation/styles.js
  client/js/screens/Contact/styles.js
  client/js/screens/Event/styles.js
  client/js/screens/Terms/styles.js
Labels: enhancement

#49 kw-add react-native-carousel library
  client/package.json
  client/yarn.lock
Labels: enhancement

#27 Kw-feature header
  client/js/assets/headingelement/Signedin.png
  client/js/navigation/config.js
Labels: enhancement

#50 Tg feature userauthasync
  client/js/components/AccountLoginForm/AccountLoginForm.js
  client/js/components/AccountLoginForm/styles.js
  client/js/components/AccountSignupForm/AccountSignupForm.js
  client/js/config/modals.js
  client/js/navigation/DrawerScreen.js
  client/js/navigation/styles.js
  client/js/screens/Home/Home.js
  client/js/screens/Login/Login.js
Labels: enhancement

#54 Username column added to comment table in schema
  server/prisma/datamodel.prisma
Labels: bug, enhancement

#53 Kw feature home
  client/js/assets/Imagery/Smokestack.png
  client/js/assets/Imagery/Wall-Street.png
  client/js/assets/Imagery/charity.png
  client/js/assets/Imagery/deadtrees.png
  client/js/assets/Imagery/gasmask.png
  client/js/assets/Imagery/revolution.png
  client/js/assets/category/Charity.png
  client/js/assets/category/Enviro.png
  client/js/assets/category/Politico.png
  client/js/assets/category/Social.png
  client/js/screens/Contact/styles.js
  client/js/screens/Home/Home.js
  client/js/screens/Home/styles.js
Labels: enhancement

#56 Create LICENSE
  LICENSE
Labels: documentation

#59 Cf feature addtocalendar
  client/ios/WRFall2019.xcodeproj/project.pbxproj
  client/ios/WRFall2019.xcodeproj/xcshareddata/xcschemes/WRFall2019-tvOS.xcscheme
  client/ios/WRFall2019.xcodeproj/xcshareddata/xcschemes/WRFall2019.xcscheme
  client/ios/WRFall2019/Base.lproj/LaunchScreen.xib
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/Contents.json
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-1024.png
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-20@3x.png
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-29@2x.png
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-29@3x.png
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-40.png
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-40@2x-1.png
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-60@2x-1.png
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-60@2x.png
  client/ios/WRFall2019/Images.xcassets/AppIcon.appiconset/World Logo Copy@5x-60@3x.png
  client/ios/WRFall2019/Info.plist
  client/js/App.js
  client/js/components/Comment/Comment.js
  client/js/components/Comment/index.js
  client/js/components/Comment/styles.js
  client/js/components/CommentCard/CommentCard.js
  client/js/components/CommentCard/index.js
  client/js/components/CommentCard/styles.js
  client/js/config/modals.js
  client/js/context/UserProvider.js
  client/js/screens/Contact/styles.js
  client/js/screens/Event/Event.js
  client/js/screens/Event/EventContainer.js
  client/js/screens/Event/styles.js
  client/js/screens/Privacy/Privacy.js
Labels: enhancement

#76 Cf feature addcalendarbutton
  client/js/components/CalendarButton/CalendarButton.js
  client/js/components/CalendarButton/index.js
  client/js/components/CalendarButton/styles.js
  client/js/screens/Campaign/Campaign.js
  client/js/screens/Campaigns/CampaignsContainer.js
  client/js/screens/Event/Event.js
  client/js/screens/Event/styles.js
Labels: enhancement

#58 Tg feature campaignconfirm
  client/js/components/MainSubscribeButton/MainSubscribeButton.js
  client/js/screens/Campaigns/Campaigns.js
  client/js/screens/Campaigns/CampaignsContainer.js
  client/js/screens/Campaigns/styles.js
  client/js/screens/Confirmation/Confirmation.js
Labels: enhancement

#68 Kw-feature editprofile
  client/js/components/AccountLoginForm/AccountLoginForm.js
  client/js/components/AccountSignupForm/AccountSignupForm.js
  client/js/components/EditProfileForm/EditProfileForm.js
  client/js/components/EditProfileForm/index.js
  client/js/components/EditProfileForm/styles.js
  client/js/config/models.js
  client/js/context/UserProvider.js
  client/js/navigation/DrawerScreen.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/config.js
  client/js/screens/EditProfile/EditProfile.js
  client/js/screens/EditProfile/EditProfileContainer.js
  client/js/screens/EditProfile/index.js
  client/js/screens/EditProfile/styles.js
  client/js/screens/Login/Login.js
Labels: enhancement

#71 Tg feature subscribebuttonlogic
  client/js/components/MainSubscribeButton/MainSubscribeButton.js
  client/js/screens/Campaign/Campaign.js
  client/js/screens/Event/Event.js
Labels: enhancement

#78 Kw-feature mycampaignslist
  client/js/components/SmallUnsubscribeButton/SmallUnsubscribeButton.js
  client/js/components/SmallUnsubscribeButton/styles.js
  client/js/screens/MyCampaigns/MyCampaigns.js
  client/js/screens/MyCampaigns/MyCampaignsContainer.js
  client/js/screens/MyCampaigns/styles.js
Labels: enhancement

#79 bugfix - Async Storage User Data
  client/ios/Podfile.lock
  client/js/App.js
  client/js/components/AccountLoginForm/AccountLoginForm.js
  client/js/components/AccountSignupForm/AccountSignupForm.js
  client/js/components/EditProfileForm/EditProfileForm.js
  client/js/config/constant.js
  client/js/config/models.js
  client/js/context/UserProvider.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/config.js
  client/js/screens/Campaign/Campaign.js
  client/js/screens/Campaign/CampaignContainer.js
  client/js/screens/Event/Event.js
  client/js/screens/Event/EventContainer.js
  client/js/screens/Home/HomeContainer.js
  client/js/screens/Login/Login.js
  client/js/screens/MyCampaigns/MyCampaignsContainer.js
Labels: bug, enhancement

#61 Tg feature onboardingasync
  client/ios/Podfile.lock
  client/js/components/AccountLoginForm/AccountLoginForm.js
  client/js/components/AccountLoginForm/styles.js
  client/js/components/AccountSignupForm/AccountSignupForm.js
  client/js/components/MainSubscribeButton/MainSubscribeButton.js
  client/js/config/models.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/AuthLoadingScreen/AuthLoadingScreenContainer.js
  client/js/screens/CampaignModal/CampaignModalContainer.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Onboarding/styles.js
Labels: enhancement

#75 Cf feature createcomment
  client/js/config/constant.js
Labels: enhancement

#82 kw-add campaign in Event Schema
  server/prisma/datamodel.prisma
Labels: enhancement

#70 Tg feature campaignmodal
  client/js/assets/miscicons/xicon.png
  client/js/components/MainSigninButton/styles.js
  client/js/navigation/RootStackNavigator.js
  client/js/screens/Campaign/Campaign.js
  client/js/screens/Campaign/styles.js
  client/js/screens/CampaignModal/CampaignModal.js
  client/js/screens/CampaignModal/CampaignModalContainer.js
  client/js/screens/CampaignModal/styles.js
Labels: enhancement

#83 add apollo-link-ws and subscriptions-transport-ws packages
  client/package.json
  client/yarn.lock
Labels: enhancement

#80 Kw-feature backbutton
  client/js/navigation/config.js
  client/js/navigation/styles.js
  client/js/screens/Campaign/CampaignContainer.js
Labels: enhancement

#86 user context bugfix
  client/ios/Podfile.lock
  client/js/navigation/NavigationLayout.js
  client/js/navigation/config.js
  client/js/screens/Campaign/CampaignContainer.js
  client/js/screens/Event/Event.js
Labels: bug, enhancement

#84 Tg feature refetchdata
  client/js/assets/miscicons/XIcon.png.orig
  client/js/assets/miscicons/XIcon2.png
  client/js/components/CampaignSubscriber/CampaigbSubscriber.js
  client/js/components/CampaignSubscriber/index.js
  client/js/components/MainSubscribeButton/MainSubscribeButton.js
  client/js/components/MainUnsubscribeButton/MainUnsubscribeButton.js
  client/js/config/api.js
  client/js/navigation/NavigationLayout.js
  client/js/screens/Campaign/Campaign.js
  client/js/screens/Campaign/CampaignContainer.js
  client/js/screens/CampaignModal/CampaignModal.js
  client/js/screens/Campaigns/CampaignsContainer.js
  client/js/screens/Confirmation/Confirmation.js
  client/js/screens/Home/Home.js
  client/js/screens/Home/styles.js
  client/package.json
  client/yarn.lock
Labels: enhancement

#87 Kw-feature notifications
  .gitignore
  server/prisma/datamodel.prisma
Labels: enhancement

#88 Kw feature notifications
  client/js/navigation/config.js
  client/js/screens/Notifications/Notifications.js
  client/js/screens/Notifications/NotificationsContainer.js
  client/js/screens/Notifications/styles.js
  server/prisma/datamodel.prisma
Labels: enhancement

#90 Tg bugfix campaignmodalremove
  client/ios/Podfile.lock
  client/js/components/MainSubscribeButton/MainSubscribeButton.js
  client/js/navigation/NavigationLayout.js
  client/js/navigation/RootStackNavigator.js
  client/js/navigation/config.js
  client/js/screens/Campaign/Campaign.js
  client/js/screens/CampaignModal/CampaignModal.js
  client/js/screens/CampaignModal/CampaignModalContainer.js
  client/js/screens/CampaignModal/index.js
  client/js/screens/Campaigns/CampaignsContainer.js
  client/js/screens/Confirmation/Confirmation.js
  client/js/screens/Login/Login.js
  client/js/screens/MyCampaigns/MyCampaignsContainer.js
  client/js/screens/Onboarding/Onboarding.js
  client/js/screens/Signup/Signup.js
  client/yarn.lock
Labels: bug, enhancement

#91 Notifications
  client/js/screens/Notifications/Notifications.js
  client/js/screens/Notifications/NotificationsContainer.js
Labels: enhancement

#63 Create code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#92 Create Readme.md
  README.md
Labels: documentation, enhancement
